before_script:
  - export APP_MIGRATION_LOOKUP=@root/tests/codeception/_migrations
  - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}
  - export TEST_IMAGE_PREFIX=buildref${CI_BUILD_REF}
  - export COMPOSE_HTTP_TIMEOUT=120
  - export HOST_APP_VOLUME=$CI_PROJECT_DIR
  - export IMAGE_NAME=phundament/app
  - mkdir -p tmp

stages:
  - build
  - test_pre
  - test
  - report
  - cleanup
  - deploy

build:
  stage: build
  script:
      - bash build/scripts/build.sh

test:
  stage: test
  script:
      - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}${CI_BUILD_NAME}
      - bash build/scripts/${CI_BUILD_NAME}.sh || EXIT_CODE=$?; cp -r tests/codeception/_output/ /tmp/${CI_BUILD_NAME}-${CI_BUILD_REF}; exit ${EXIT_CODE}

test-allow_failure:
  stage: test_pre
  script:
      - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}${CI_BUILD_NAME}
      - set +e
      - bash build/scripts/${CI_BUILD_NAME}.sh || EXIT_CODE=$?
      - set -e
      - cp -r tests/codeception/_output/ /tmp/${CI_BUILD_NAME}-${CI_BUILD_REF}
      - exit ${EXIT_CODE}
  allow_failure: true
  only:
      - develop

system:
  stage: test
  script:
      - bash build/scripts/system.sh
  allow_failure: true

report:
  stage: report
  script:
    - sleep 5 # waiting for copy task
    - ls -lat /tmp
  artifacts:
    paths:
      - /tmp/test-${CI_BUILD_REF}
      - /tmp/test-allow_failure-${CI_BUILD_REF}
  when: always

cleanup:
  stage: cleanup
  script:
    - make TEST clean
    - export COMPOSE_PROJECT_NAME="buildref${CI_BUILD_REF}test"
    - make TEST clean
    - export COMPOSE_PROJECT_NAME="buildref${CI_BUILD_REF}test-allow_failure"
    - make TEST clean
    - rm -rf /tmp/test-${CI_BUILD_REF}
    - rm -rf /tmp/test-allow_failure-${CI_BUILD_REF}
  when: always

deploy:
  stage: deploy
  script:
      - bash build/scripts/deploy.sh
  only:
      - master
      - /^[0-9]+\.[0-9]+.*$/
