job:
    script:
        - "export CI_APP_VOLUME=/srv/gitlab-runner/$CI_PROJECT_DIR"
        - "bash build/ci/test.sh"
    stage: test

deploy:
    script:
        - export REGISTRY_HOST=index.docker.io
        - export REGISTRY_USER=schmunk42
        - export PROJECT_REGISTRY=phundament/app
        - "cp .env-dist .env"
        - "bash build/ci/deploy.sh"
    stage: deploy
