# GitLab CI configuration

test & push:
  script:
  - export DOCKER_CLIENT_TIMEOUT=120
  - export REGISTRY_HOST="index.docker.io"
  - export REGISTRY_USER="schmunk42"
  - export PROJECT_REGISTRY="phundament"
  - export IMAGE_NAME="app"
  - export DB_ENV_MYSQL_DATABASE=myapp-2-ci
  - build/ci/test.sh
