before_script:
  - export APP_MIGRATION_LOOKUP=@root/tests/codeception/_migrations
  - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}
  - export COMPOSE_HTTP_TIMEOUT=120
  - export HOST_APP_VOLUME=$CI_PROJECT_DIR
  - export IMAGE_NAME=phundament/app
  - cp build/compose/test.override.yml docker-compose.override.yml

stages:
  - build
  - test
  - cleanup_test
  - deploy

build:
  stage: build
  script:
      - bash build/scripts/build.sh

test:
  stage: test
  script:
      - bash build/scripts/test.sh
      - mv tests/codeception/_output/ reports-${CI_BUILD_ID}
  artifacts:
    paths:
      - reports-${CI_BUILD_ID}

test-dev:
  stage: test
  script:
      - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}${CI_BUILD_NAME}
      - bash build/scripts/test-dev.sh
      - mv tests/codeception/_output/ reports-dev-${CI_BUILD_ID}
  artifacts:
    paths:
      - reports-dev-${CI_BUILD_ID}
  allow_failure: true

system:
  stage: test
  script:
      - bash build/scripts/system.sh
  allow_failure: true

cleanup_test:
  stage: cleanup_test
  script:
    - make TEST clean
    - make clean COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}test-dev
  when: always

deploy:
  stage: deploy
  script:
      - bash build/scripts/deploy.sh
  only:
      - master
