job:
    script:
        - "export CI_APP_VOLUME=/srv/gitlab-runner/$CI_PROJECT_DIR"
        - "bash build/ci/test.sh"
    stage: test

deploy:
    script:
        - "cp .env-dist .env"
        - "bash build/ci/deploy.sh"
    stage: deploy
