language: php

php:
  - 5.4
  - 5.5
#  - 5.6
#  - hhvm

# run build against PHP 5.6 and hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6

install:
  - composer self-update && composer --version
# basic application:
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta2"
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer install --dev --prefer-dist
  - ./init --env=Development --overwrite=n

before_script:
  - mysql -e 'create database p4_test;'
  - mysql -e "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev123';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'dev'@'localhost';"
  - php yii app/setup-tests --interactive=0

script:
  - php ~/.composer/vendor/bin/codecept run -c tests/
