language: php

php:
  - 5.4
  - 5.5
#  - 5.6
#  - hhvm

# run build against PHP 5.6 and hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6

install:
  - composer self-update && composer --version
# basic application:
  - composer install --dev --prefer-dist
  - php yii app/setup-tests

script:
  - php vendor/bin/codecept run -c tests/
