language: php

php:
  - 5.4
  - 5.5
  - 5.6
#  - hhvm

# run build against PHP 5.6 and hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6

env:
  global:
    - DATABASE_DSN="mysql:host=localhost;dbname=p4"
    - DATABASE_USER=dev
    - DATABASE_PASSWORD=dev123
    - TEST_DATABASE_DSN="mysql:host=localhost;dbname=p4_test"
    - TEST_DATABASE_USER=dev
    - TEST_DATABASE_PASSWORD=dev123

install:
  - composer self-update && composer --version
# basic application:
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
  - cp .env-dist .env
  - composer install --dev --prefer-dist

before_script:
  - mysql -e 'create database p4_test;'
  - mysql -e "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev123';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'dev'@'localhost';"
  - php yii app/setup-tests --interactive=0

script:
  - php yii app/run-tests --interactive=0
