language: php

php:
  - 5.3

before_script:
    - composer install --prefer-dist
    - cp app/config/local-dist.php app/config/local.php
    - composer install --dev --prefer-dist
    - composer require --dev "codeception/codeception:@stable"
    - app/yiic migrate --connectionID=dbTest --interactive=0
    - chmod 777 app/data/test.db
    - sed -i '.orig' 's|ENTER_YOUR_PHUNDAMENT_URL_HERE|localhost/www|' "app/tests/codeception/acceptance.suite.yml"

script: ./vendor/bin/codecept.phar run -c`pwd`

env:
    - PHUNDAMENT_TEST=true

branches:
  only:
    - master