# Phundament 4 - Application stack

php:
  build: .
  links:
    - 'postgres:DB'
  environment:
    - DATABASE_DSN_BASE=pgsql:host=db
    - DATABASE_DSN_DB=pg
    - DATABASE_USER=pg
    - DATABASE_PASSWORD=dev123

nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'

postgres:
  image: 'postgres'
  environment:
    POSTGRES_USER: pg
    POSTGRES_PASSWORD: dev123
