# Phundament 4 - Local Development Stack
# ======================================

# Application services
# --------------------

php:
  build: .
  links:
    - 'mariadb:DB'
  volumes:
    - .:/app
  #environment:
  #  APP_MIGRATION_LOOKUP: '@app/migrations'

nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'
  volumes:
    - .:/app

mariadb:
  image: 'tutum/mariadb:10.1'
  environment:
    MARIADB_PASS: secretadmin