# Phundament 4 - Local Development Stack
# ======================================

# Application services
# --------------------

# container to run one-off commands - a dockerized shell
appcli:
  # should be replaced with: image: <project_name>_appsrc
  image: project_appsrc
  # host-volume for local development
  volumes:
    - '.:/app'
  links:
    - 'appnginx:WEB'
    - 'mariadb:DB'
  environment:
    APP_MIGRATION_LOOKUP: '@app/migrations'
  command: 'tail -f /dev/null'

appsrc:
  build: .
  # host-volume for local development
  volumes:
    - '.:/app'
  command: 'tail -f /dev/null'

# The php-fpm server for interpreting php code
appfpm:
  image: phundament/php:5.6-fpm-dev
  # host-volume for local development
  volumes:
    - '.:/app'
  links:
    - 'mariadb:DB'

# The nginx server for serving static files directly
appnginx:
  image: schmunk42/nginx:1.7
  links:
    - 'appfpm:PHPFPM'
  # host-volume for local development
  volumes:
    - '.:/app'
    #- 'build/nginx/run.sh:/root/run.sh'
  ports:
    - '80'
  environment:
    VIRTUAL_HOST: '~^dev\.khf\.com'

# Data Services
# -------------
mariadb:
  image: tutum/mariadb:10.1
  ports:
    - '3306'
  environment:
    MARIADB_PASS: secretadmin
