# Phundament 4 - Local development overrides

php:
  volumes:
    - .:/app
    - /Users/tobias/hrzg/git/phundament/ee-docs:/app/docs-ext
nginx:
  ports:
    - '40080:80'
  volumes:
    - .:/app
mariadb:
  ports:
    - '43306:3306'
