---
vagrantfile:
    vm:
        # TODO: check box Linux Distribution, Values are changed for AWS in Vagrantfile(!)
        box: debian-wheezy72-x64-vbox43
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.33.101
            forwarded_port:
                XQ8lS2HbWblh:
                    host: '10122'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            aws:
                # NOTICE: usage of ENV vars in Vagrantfile
                access_key_id: #AWSAccessKeyId
                secret_access_key: #AWSSecretKey
                keypair_name: #AWSKeypairName
                ami: ami-a850c898
                region: us-west-2
                instance_type: t1.micro
                security_groups:
                    - launch-wizard-1
            digital_ocean:
                image: 'Debian 7.0 x64'
                region: 'Amsterdam 1'
                size: 1GB
                client_id: #DIGITAL_OCEAN_CLIENT_ID
                api_key: #DIGITAL_OCEAN_API_KEY
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            Mrgp6xPR893x:
                # TODO: implement params dmode and fmode for usage in Vagrantfile
                id: vagrant-root
                source: ./
                target: /var/www/phundament.vagrant
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        path: /usr/local/bin
        log: /var/log/mailcatcher/mailcatcher.log
apache:
    modules:
        - php
        - rewrite
    vhosts:
        SuaWo9TvBE9J:
            priority: 1
            servername: phundament.vagrant
            docroot: /var/www/phundament.vagrant/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
    mod_pagespeed: 0
    mod_spdy: 0
php:
    version: '54'
    composer: '1'
    modules:
        php:
            - apc
            - cli
            - intl
            - mcrypt
            - curl
            - sqlite
            - xsl
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    root_password: '123'
    phpmyadmin: '1'
    adminer: 0
    databases:
        5pcZ94aBG8kL:
            grant:
                - ALL
            name: phundament
            host: localhost
            user: phundament
            password: phundament
            sql_file: ''
mongodb:
    install: '0'
    auth: 1
    port: '27017'
    databases: {  }
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    port: '5672'
